### ISSUE TITLE
Bindings do not allow brackets in bind-value

### ISSUE THREAD

**Issue by knappe** [chip-js/chip#8]
Yesterday we discovered a bug with bindings where brackets are not parsed.  For example,

`<div bind-if="sendTo[AVAILABILITIES.NONE]">`

Fails and events are not fired as expected.  We should allow brackets to be used.

**Comment by jacwright** [comment]
Fixed in the new https://github.com/chip-js/expressions module, available in chip 1.1 and 2.0
